name: decommission alert

on:
  push:
  schedule:
    - cron: "0 12 * * *"  # Auto-triggers everyday at 5:30 PM IST
  pull_request:
    types: [opened, closed]
  pull_request_review:
    types: [submitted]
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  generate_decommission_alert:
    if: github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Check repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate decommission countdown image
        run: python generate_decommission_alert.py

      - name: Commit and push updated GIF
        if: github.ref == 'refs/heads/Dev' || github.ref == 'refs/heads/Dev'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/decommission_alert.gif
          git add docs/decommission_alert_banner.jpg
          git add docs/decommission_alert_large.jpg
          git add docs/decommission_alert_small.jpg
          git add docs/decommission_alert_medium.jpg
          git commit -m "Update decommission alert GIF [skip ci]" || echo "No changes to commit"
          git push

